version: '3'
services:
  mp4:
    build: .
    ports:
      - "80:5000"
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    volumes:
      - ./app:/srv/app
